theme: jekyll-theme-minimal
kramdown:
  parse_block_html: true
logo: assets/img/blueocean-swoosh.svg
show_downloads: false
is_user_page: false
is_project_page: true
github:
  repository_url: https://github.com/jenkinsci/jenkins-design-language
  description: React components for Jenkins Blue Ocean
  project_tagline: React library for Jenkins Blue Ocean
